// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace GameLibrary.AutomatedTests.Developers
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CreateDeveloperFeature : Xunit.IClassFixture<CreateDeveloperFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CreateDeveloper.feature"
#line hidden
        
        public CreateDeveloperFeature(CreateDeveloperFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "CreateDeveloper", "\tUm usuário acessa a tela de cadastro, \r\n\tpreenche os dados do cadastro e salva o" +
                    " registro\t", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Cadastro de Developer")]
        [Xunit.TraitAttribute("FeatureTitle", "CreateDeveloper")]
        [Xunit.TraitAttribute("Description", "Cadastro de Developer")]
        [Xunit.TraitAttribute("Category", "TesteAutomatizadoCadastroDeveloperSucesso")]
        public virtual void CadastroDeDeveloper()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastro de Developer", null, new string[] {
                        "TesteAutomatizadoCadastroDeveloperSucesso"});
#line 6
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 7
 testRunner.Given("clica no link da area de developer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 8
 testRunner.And("Acessa a tela de cadastro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Campo",
                        "Valor"});
            table1.AddRow(new string[] {
                        "name",
                        "Nintendo"});
            table1.AddRow(new string[] {
                        "founded",
                        "23/09/1889"});
            table1.AddRow(new string[] {
                        "webSite",
                        "http://nintendo.com"});
#line 9
 testRunner.And("Preenche os dados do formulario", ((string)(null)), table1, "E ");
#line 14
 testRunner.When("Clica no botao Cadastrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 15
 testRunner.Then("Recebe uma mensagem de developer cadastrado  com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 16
 testRunner.And("exclui o developer cadastrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Cadastro de Developer sem nome")]
        [Xunit.TraitAttribute("FeatureTitle", "CreateDeveloper")]
        [Xunit.TraitAttribute("Description", "Cadastro de Developer sem nome")]
        [Xunit.TraitAttribute("Category", "TesteAutomatizadoCadastroDeveloperFalha")]
        public virtual void CadastroDeDeveloperSemNome()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastro de Developer sem nome", null, new string[] {
                        "TesteAutomatizadoCadastroDeveloperFalha"});
#line 19
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 20
 testRunner.Given("clica no link da area de developer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 21
 testRunner.And("Acessa a tela de cadastro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Campo",
                        "Valor"});
            table2.AddRow(new string[] {
                        "name",
                        ""});
            table2.AddRow(new string[] {
                        "founded",
                        "23/09/1889"});
            table2.AddRow(new string[] {
                        "webSite",
                        "http://nintendo.com"});
#line 22
 testRunner.And("Preenche os dados do formulario", ((string)(null)), table2, "E ");
#line 27
 testRunner.Then("Recebe uma mensagem de nome obrigatorio", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line 28
 testRunner.And("exclui o developer cadastrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Cadastro de Developer com data futura")]
        [Xunit.TraitAttribute("FeatureTitle", "CreateDeveloper")]
        [Xunit.TraitAttribute("Description", "Cadastro de Developer com data futura")]
        [Xunit.TraitAttribute("Category", "TesteAutomatizadoCadastroDeveloperFalha")]
        public virtual void CadastroDeDeveloperComDataFutura()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastro de Developer com data futura", null, new string[] {
                        "TesteAutomatizadoCadastroDeveloperFalha"});
#line 31
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 32
 testRunner.Given("clica no link da area de developer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 33
 testRunner.And("Acessa a tela de cadastro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Campo",
                        "Valor"});
            table3.AddRow(new string[] {
                        "name",
                        "Nintendo"});
            table3.AddRow(new string[] {
                        "founded",
                        "23/09/2100"});
            table3.AddRow(new string[] {
                        "webSite",
                        "http://nintendo.com"});
#line 34
 testRunner.And("Preenche os dados do formulario", ((string)(null)), table3, "E ");
#line 39
 testRunner.When("Clica no botao Cadastrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 40
 testRunner.Then("Recebe uma mensagem de data de fundacao invalida", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CreateDeveloperFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CreateDeveloperFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
